[versions]
activityKtx = "1.12.1"
agp = "8.13.2"
fragmentKtx = "1.8.9"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"

junitVersion = "1.3.0"
espressoCore = "3.7.1"
appcompat = "1.7.1"
lifecycleViewmodelKtx = "2.10.0"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
retrofit = "3.0.0"
kotlinx-serialization = "1.9.0"
retrofit-kotlinx-serialization = "1.0.0"
okhttp-logging = "5.3.2"
coil = "3.3.0"
lifecycleRuntimeKtx = "2.10.0"
material3 = "1.4.0"
mpandroidchart = "3.1.0"
timber = "4.7.1"
joda-time = "2.13.0"
startup = "1.2.0"
koin = "4.1.1"
datastore = "1.2.0"
kotlinx-coroutines = "1.8.0"

[libraries]
coil-kt-coil = { module = "io.coil-kt:coil" }
gson = { module = "com.google.code.gson:gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

philjay-mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-kotlinx-serialization" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
joda-time = { module = "joda-time:joda-time", version.ref = "joda-time" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }

androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

[bundles]
ui-core = ["androidx-activity-ktx", "androidx-fragment-ktx",
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-appcompat", "material", "androidx-activity",
]
network = ["retrofit", "converter-gson", "retrofit-kotlinx-serialization-converter", "okhttp-logging-interceptor"]
koin = ["koin-core", "koin-android", "androidx-startup"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

